"""Add simulated_hour to Tracking

Revision ID: 0aa2d2f80c76
Revises: 
Create Date: 2025-03-28 12:57:16.430608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0aa2d2f80c76'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('geofences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('coordinates', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tracking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('user_name', sa.String(length=100), nullable=False),
    sa.Column('geofence_id', sa.Integer(), nullable=False),
    sa.Column('geofence_name', sa.String(length=100), nullable=False),
    sa.Column('event_type', sa.String(length=20), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('simulated_hour', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['geofence_id'], ['geofences.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tracking')
    op.drop_table('geofences')
    # ### end Alembic commands ###
